#!/bin/bash
#basic script to set iptables

#check sudo privileges
if [[ $EUID -ne 0 ]]
then
    echo -e "run as root"
    exit 1
fi
echo -e "Consolidating rules\nyou should have restarted the connection"
/sbin/service iptables save
